microsoft/vscode-livepreview

.github/workflows/build.yml
Adding Github Actions for CI - code linting and building.
=> Adding Github Actions

.github/workflows/build.yml, .prettierrc.yaml, .vscode/launch.json, README.md, media/inject_script.js, media/main.js, package-lock.json, package.json, src/browserPreview.ts, src/constants.ts, src/extension.ts, src/manager.ts, src/pageHistoryTracker.ts, src/server.ts, src/utils.ts, test-workspace/page2.html
Basic pages for some cases where user content isn't shown. Customizations to make this less plain (ie: adding icons) can be added later.
Support for index pages in place for when an `index.html` file .
[![Image from Gyazo](https://i.gyazo.com/990095868481026d8b5b847e2f15ed7c.gif)](https://gyazo.com/990095868481026d8b5b847e2f15ed7c)
Also has a page for when the file cannot be found.
Also added code formatting and some modifications to CI to make it work.
=> Index Pages and Page Not Found

src/server.ts, test-workspace/styles.css
Taking out references to fonts like Consolas and Calibri, since they don't seem to show on Linux.
Also some re-formatting for cleaning up.
=> Font Changes for Multi-OS Support

.gitignore, .vscode/launch.json, .vscodeignore, README.md, codicon_copy.js, package-lock.json, package.json, src/browserPreview.ts, src/server.ts, webpack.config.js
- Adding webpack scripts for bundling; reduced `*.vsix` size from ~45MB to ~6MB.
- Removed slash from end of filenames
Fixes https://github.com/microsoft/vscode/issues/125178
=> bundling and minor fixes

package-lock.json, package.json, webpack.config.js
Changing webpack configuration so that:
- All output files are in `out/` and the extra files are in `media/`
- Deleting all files in `out/` before re-building webpack
=> Bundling Refinement

package.json, src/editorPreview/browserPreview.ts, src/extension.ts, src/manager.ts, src/server/mainServer.ts, src/server/serverManager.ts, src/server/serverUtils/statusBarNotifier.ts, src/utils/constants.ts, src/utils/utils.ts
Addresses feature here: https://github.com/microsoft/vscode/issues/125855
Adding settings to live server to allow user to customize experience. Some settings are configurable according to what they select on pop-up messages.
Closes https://github.com/microsoft/vscode/issues/125855
=> User Settings

media/inject_script.html, media/main.js, media/preview-dark.svg, media/preview-light.svg, media/vscode.css, src/editorPreview/browserPreview.ts, src/extension.ts, src/server/httpServer.ts, src/server/serverManager.ts, src/server/serverUtils/contentLoader.ts, src/server/wsServer.ts, src/utils/constants.ts, src/utils/utils.ts
Addressed suggestions featured in https://github.com/microsoft/vscode/issues/125949
I made the UX look a lot more like how the simple browser looks.
[![Image from Gyazo](https://i.gyazo.com/42fd2ee6cb7c3c44d74ff2887b1c445e.gif)](https://gyazo.com/42fd2ee6cb7c3c44d74ff2887b1c445e)
Also modified how external links are opened:
[![Image from Gyazo](https://i.gyazo.com/9f2be0f421439fd30065f7bba44a42f0.gif)](https://gyazo.com/9f2be0f421439fd30065f7bba44a42f0)
Closes https://github.com/microsoft/vscode/issues/125949
=> UX Optimizations

src/editorPreview/browserPreview.ts, src/extension.ts, src/manager.ts, src/server/httpServer.ts, src/server/serverManager.ts, src/server/serverUtils/contentLoader.ts, src/server/wsServer.ts, src/task/serverTaskProvider.ts, src/task/serverTaskTerminal.ts, src/utils/utils.ts
As written in title; causes less empty telemetry events.
=> Changing Telemetry to be More Category-based

media/inject_script.html, media/main.js
Some cleanup / organization on the JS side of the extension.
=> Script Cleanup

media/inject_script.html, media/main.js, media/vscode.css, package-lock.json, package.json, src/editorPreview/browserPreview.ts
Link preview in bottom left corner on hover.
Example:
[![Image from Gyazo](https://i.gyazo.com/7cb4bb744a6922ddb6f09199e0da3c6c.gif)](https://gyazo.com/7cb4bb744a6922ddb6f09199e0da3c6c)
Closes https://github.com/microsoft/vscode/issues/127019
=> Link Preview

README.md, media/inject_script.html, package-lock.json, package.json, src/extension.ts, src/manager.ts, src/server/serverUtils/HTMLInjector.ts, src/server/serverUtils/contentLoader.ts, src/server/serverUtils/endpointManager.ts, src/task/serverTaskProvider.ts, src/task/serverTaskTerminal.ts, src/utils/settingsUtil.ts
As described in title, and fixed bug with opening external window with a non-workspace file.
=> Changed name to `Live Preview'

media/inject_script.html, media/main.js, src/editorPreview/browserPreview.ts, src/extension.ts, src/manager.ts, src/server/httpServer.ts, src/server/serverManager.ts, src/task/serverTaskLinkProvider.ts, src/task/serverTaskProvider.ts
Cleaning up code to abstract away the link provider and fixing a few minor bugs.
=> Code Cleanup and Minor Bugfixes

package.json, src/editorPreview/browserPreview.ts, src/extension.ts, src/manager.ts, src/server/wsServer.ts, src/utils/settingsUtil.ts
Fixed the bugs:
- `External Preview at Index` fixed
- Opening external preview from internal now doesn't show warning.
- More descriptive command names where necessary.
=> Small Bugfixes

media/inject_script.html, media/main.js, media/vscode.css, package-lock.json, package.json, src/editorPreview/browserPreview.ts, src/extension.ts, src/infoManagers/workspaceManager.ts, src/manager.ts, src/server/httpServer.ts, src/task/serverTaskLinkProvider.ts, src/task/serverTaskProvider.ts, src/utils/settingsUtil.ts
Allow for tab + arrow key navigation for top navigation bar in embedded preview. The group of buttons for back/forth/reload is one tab group that can use arrow keys to navigate between.
Closes https://github.com/microsoft/vscode/issues/127437
Fixed vertical alignment of nav keys
Closes https://github.com/microsoft/vscode/issues/127445
Fixed refresh border focus persisting after click
Closes https://github.com/microsoft/vscode/issues/127448
Fixed bug where having spaces in filename caused a bug.
Closes https://github.com/microsoft/vscode/issues/127629
Improved multi-workspace add/remove support (still has bug with adding workspace from single workspace).
Allow terminal links to appear to the side.
Closes https://github.com/microsoft/vscode/issues/127459
=> More UX Changes and Bugfixes (Testplan)

package.json, src/extension.ts, src/manager.ts, src/utils/settingsUtil.ts
- Default "Start Server" setting changed to be for workspace settings instead of user settings.
- Fixed bug with filenames with spaces saved as setting for default server open file.
- Misc typo correction and organization (cleanup)
=> Bugfixes from Recent Features

package-lock.json, package.json, src/utils/settingsUtil.ts
Using camel case for settings.
Closes #53
=> Settings Rename

media/inject_script.html
Applied changes suggested in #68 to reduce redundant parent messages. 
Closes #68
=> Fix High CPU Use (External Browser)

package.json, src/editorPreview/webviewComm.ts, src/extension.ts, src/infoManagers/endpointManager.ts, src/infoManagers/workspaceManager.ts, src/manager.ts, src/server/serverManager.ts, src/task/serverTaskLinkProvider.ts, src/utils/pathUtil.ts, src/utils/settingsUtil.ts
Added `livePreview.watchFiles` setting to specify watch files.
Closes #51
Changed Default Preview Path to be relative to workspace root.
Closes #44
=> Custom Settings Modifications

media/inject_script.html, media/main.js, media/vscode.css, package.json, src/editorPreview/browserPreview.ts, src/manager.ts, src/task/serverTaskTerminal.ts, src/utils/terminalStyleUtil.ts
Piping `console.log()` statements from the project's scripts to an output channel. Simply performs a `JSON.stringify()` on the console contents, so may not show elements stringified nicely due to limitations of the output channel.
[![Image from Gyazo](https://i.gyazo.com/c0b3569e3524ac256c65e97109648369.gif)](https://gyazo.com/c0b3569e3524ac256c65e97109648369)
Closes #77
=> Add Console output to Output Channel

package.json, src/server/serverManager.ts, src/utils/pathUtil.ts, src/utils/settingsUtil.ts
The new file watching should be able to track changes outside of the editor.
[![Image from Gyazo](https://i.gyazo.com/0a6f7bcbb2a6a53439c64afcfb854a48.gif)](https://gyazo.com/0a6f7bcbb2a6a53439c64afcfb854a48)
Closes #81
Closes #51
=> Implement Better File Watching

src/infoManagers/connectionManager.ts, src/task/serverTaskProvider.ts, src/utils/constants.ts
Closes #140 
Closes #141 
Tested on stable + insiders
=> Fixed Custom IP Error on Local Session + Fixed Identical Task Names

build/pipeline.yml, package.json, package.nls.json, src/extension.ts, src/manager.ts, src/setupNls.ts, src/utils/constants.ts, webpack.config.js, yarn.lock
I started you off with a couple strings. More should be added, but it all works:
* a string in the manifest (Live Server: Start Server)
* a string in code (Output channel name)
=> Onboard to localization pipeline

media/main.js, src/extension.ts, src/server/httpServer.ts, src/utils/pathUtil.ts, test-workspace/测试目录/page.html, test-workspace/测试目录/测试.html
1. Open the Chinese path file normally
2. The address bar decode
3. 404 path
Fixes #131
=> fix #224 Support Chinese

package.json
=> bump version to 0.2.13

.github/workflows/pr-chat.yml
Onboards live preview to the code review channel
=> Onboard to Codereview Channel

media/injectScript.js, media/main.js, package.json, package.nls.json, src/editorPreview/browserPreview.ts, src/editorPreview/webviewComm.ts, src/extension.ts, src/infoManagers/connectionManager.ts, src/manager.ts, src/server/httpServer.ts, src/server/serverManager.ts, src/server/serverUtils/HTMLInjector.ts, src/server/serverUtils/contentLoader.ts, src/server/serverUtils/statusBarNotifier.ts, src/server/wsServer.ts, src/setupNls.ts, src/task/serverTaskLinkProvider.ts, src/task/serverTaskTerminal.ts, src/utils/constants.ts
Fixes #221
Added localization and also formatted code.
=> Localize rest of strings

README.md, package.json
=> Change Activation and Remove Prereq on README

package.json, package.nls.json, src/server/serverUtils/statusBarNotifier.ts, src/utils/settingsUtil.ts
Fixes #273
Fixes #280
Fixes #269
=> updated status bar and activate extension on set default path

src/server/httpServer.ts
=> only loose workspace server should serve loose files

src/manager.ts, src/server/serverUtils/contentLoader.ts, src/utils/settingsUtil.ts
=> fix debugger issues

media/main.js, src/editorPreview/browserPreview.ts
=> fix handling non-injectable paths

src/server/serverUtils/contentLoader.ts, src/server/serverUtils/statusBarNotifier.ts
=> Workspace names in status bar tooltip

CHANGELOG.md
Things should be in place for the August release.
=> Change 0.4.0 release for tomorrow

media/main.js, src/manager.ts, src/server/serverGrouping.ts, src/server/serverUtils/statusBarNotifier.ts, src/updateListener.ts
=> isolated listeners into singleton and fixed out-of-workspace refresh

src/editorPreview/browserPreview.ts, src/editorPreview/previewManager.ts, src/editorPreview/webviewComm.ts, src/extension.ts, src/manager.ts, src/server/serverGrouping.ts, src/server/serverUtils/HTMLInjector.ts, src/server/serverUtils/statusBarNotifier.ts, src/task/serverTaskLinkProvider.ts, src/task/serverTaskProvider.ts, src/task/serverTaskTerminal.ts
Remove unecessary string paths.
Fixes #320
=> URI refactoring

package.json, package.nls.json, src/editorPreview/browserPreview.ts, src/extension.ts, src/manager.ts, src/server/serverGrouping.ts, src/task/serverTaskLinkProvider.ts, src/task/serverTaskProvider.ts, src/task/serverTaskTerminal.ts
=> Task cleanup and add command for running task

src/connectionInfo/connection.ts, src/manager.ts, src/task/serverTaskLinkProvider.ts, src/task/serverTaskTerminal.ts, src/utils/utils.ts
=> Clicking on the "started" URL in the task terminal doesn't open in default preview

src/extension.ts, src/manager.ts, src/server/serverGrouping.ts
=> fix server launch when server already opening

package.json, src/editorPreview/browserPreview.ts, src/manager.ts
=> Add ability to open external preview from internal preview via command palette

src/manager.ts
=> Fix webview reserialization on reload

package.json, src/connectionInfo/connection.ts, src/connectionInfo/connectionManager.ts, src/editorPreview/browserPreview.ts, src/editorPreview/pageHistoryTracker.ts, src/editorPreview/previewManager.ts, src/editorPreview/webviewComm.ts, src/extension.ts, src/infoManagers/endpointManager.ts, src/manager.ts, src/server/httpServer.ts, src/server/serverGrouping.ts, src/server/serverUtils/HTMLInjector.ts, src/server/serverUtils/contentLoader.ts, src/server/serverUtils/statusBarNotifier.ts, src/server/wsServer.ts, src/task/serverTaskLinkProvider.ts, src/task/serverTaskProvider.ts, src/task/serverTaskTerminal.ts, src/updateListener.ts, src/utils/constants.ts, src/utils/pathUtil.ts, src/utils/settingsUtil.ts, src/utils/terminalStyleUtil.ts, src/utils/utils.ts, yarn.lock
Fixes #314
Also removes unused imports
=> Add copyright headers

package.json, yarn.lock
packaging is failing https://dev.azure.com/monacotools/Monaco/_build/results?buildId=187779&view=logs&j=eb79cae4-0ffb-5516-9c82-40a537d0707b&t=69f51026-bb55-5158-b1d4-437b898d051c
=> fix failing packaging

README.md, package.json
=> bump version 0.4.2 and readme update

src/server/httpServer.ts
=> Fix origin check

package.json
=> fix context for external previews

CHANGELOG.md, package.json
=> add details for patch release

src/server/httpServer.ts
=> Can't preview an HTML file in a Codespace

src/server/serverGrouping.ts, src/task/serverTaskProvider.ts
=> fix external preview open command when server is closed

media/injectScript.js, media/main.js, src/server/httpServer.ts, src/task/serverTaskProvider.ts
Fixes #153
Fixes #377
Fixes #226
Main fixes:
- Cleaning up bad code in `main.js` and `injectedScript.js` from last summer.
- Fixing bug with using `ctrl`+`shift`+`F`
=> Cleaning up media files

src/extension.ts, src/manager.ts
=> Don't have extra quickpick when closing server when one server open.

package.json, package.nls.json
=> remove `livePreview.tasks.browserPreviewLaunchServerLogging`

src/connectionInfo/connection.ts, src/editorPreview/browserPreview.ts, src/editorPreview/previewManager.ts, src/extension.ts, src/infoManagers/endpointManager.ts, src/manager.ts, src/server/httpServer.ts, src/server/serverGrouping.ts, src/server/serverUtils/HTMLInjector.ts, src/server/serverUtils/contentLoader.ts, src/server/wsServer.ts, src/task/serverTaskLinkProvider.ts, src/utils/pathUtil.ts
=> Avoid fs sync APIs

src/editorPreview/previewManager.ts
=> serverKeepAliveAfterEmbeddedPreviewClose = 0 fix

src/connectionInfo/connection.ts, src/editorPreview/pageHistoryTracker.ts, src/editorPreview/previewManager.ts, src/editorPreview/webviewComm.ts, src/extension.ts, src/infoManagers/endpointManager.ts, src/manager.ts, src/server/serverGrouping.ts, src/utils/pathUtil.ts, src/utils/settingsUtil.ts
Fixes #275
Fixes #274
Plus extra cleanup
=> Standardize on / for paths in settings and set relative paths when possible

package.json, package.nls.json, src/editorPreview/browserPreview.ts, src/editorPreview/previewManager.ts, src/utils/externalBrowserUtils.ts, src/utils/settingsUtil.ts, src/utils/utils.ts, yarn.lock
Fixes #69
Uses npm [open](https://www.npmjs.com/package/open) package
=> Add option to choose default external browser

src/manager.ts, src/utils/externalBrowserUtils.ts
Fixes #415
Fixes https://github.com/microsoft/vscode-livepreview/issues/414
=> Fix external browser opening on codespaces

src/manager.ts
=> Fix openPreviewAtFileString opening absolute paths

README.md
Fixes #418
Updates:
- updated out-of-workspace message to reflect `livePreview.serverRoot` setting
- corrected codespaces fix method
- added question for embedded/external discrepency.
=> update readme FAQ

src/server/wsServer.ts
=> Non-injectable detected incorrectly

README.md, src/editorPreview/previewManager.ts
=> Outside of server root warning doesn't consider new server root setting

package.json, package.nls.json, src/connectionInfo/connection.ts, src/utils/settingsUtil.ts
Fixes #430
Fixes #428
Fixes #424
=> Fix setting clarity and setting not updating while server is up

package.json, src/editorPreview/browserPreview.ts, src/editorPreview/previewManager.ts, src/extension.ts, src/manager.ts, src/server/serverGrouping.ts, src/utils/pathUtil.ts, src/utils/settingsUtil.ts
=> make default preview path `"scope": "resource"`

src/extension.ts
=> Server Start should start on the active workspace

src/editorPreview/browserPreview.ts, src/infoManagers/endpointManager.ts, src/server/httpServer.ts, src/server/serverUtils/HTMLInjector.ts, src/server/serverUtils/contentLoader.ts, src/task/serverTaskLinkProvider.ts, src/task/serverTaskTerminal.ts
=> substr -> substring since substr is deprecated

src/infoManagers/endpointManager.ts
=> fix out-of-workspace preview with unix paths

src/infoManagers/endpointManager.ts
=> out-of-workspace UNC paths not working

package.json, package.nls.json, src/server/httpServer.ts, src/utils/constants.ts, src/utils/settingsUtil.ts
=> add customizable http headers

.vscode/launch.json, package.json, src/utils/externalBrowserUtils.ts, yarn.lock
Fixes #517
Uses the js-debug companion as a dependency for opening a custom browser.
=> Support custom external browser on remote cases (SSH, Dev Container)

src/server/httpServer.ts, src/server/serverUtils/contentLoader.ts
Changing `currentTime` of `HTMLAudioElement` requires that `Content-Length` exists in response header.
```js
const audio = new Audio()
audio.ondurationchange = function () {
console.log(`ondurationchange: ${audio.duration}`)
}
audio.oncanplay = function () {
audio.play()
}
const playButton = document.createElement('button')
playButton.innerText = 'play'
playButton.onclick = function () {
audio.src = './FloralLife.mp3'
}
const setButton = document.createElement('button')
setButton.innerText = 'set current time'
setButton.onclick = function () {
audio.currentTime = 20 // require Content-Length
}
document.body.append(audio)
document.body.append(playButton)
document.body.append(setButton)
```
Fixes #549
=> Add Content-Length to response header

src/server/httpServer.ts
=> Make sure CORP headers are sent

README.md
Ref https://github.com/microsoft/vscode-livepreview/issues/566#issuecomment-1817132701
=> update readme to state livePreview.autoRefreshPreview

src/server/httpServer.ts, yarn.lock
=> Add require-corp header

CHANGELOG.md, package.json, src/server/httpServer.ts, yarn.lock
Reverts microsoft/vscode-livepreview#571
This was causing issues with iframes and images linking.
Fixes https://github.com/microsoft/vscode-livepreview/issues/579
Fixes https://github.com/microsoft/vscode-livepreview/issues/578
Fixes https://github.com/microsoft/vscode-livepreview/issues/577
=> Revert "Add require-corp header"

package.json
This was mistakenly added for https://github.com/microsoft/vscode-livepreview/issues/277, but it doesn't actually work yet.
=> remove task icon code

.vscode/settings.json, package.json
Fixes https://github.com/microsoft/vscode-livepreview/issues/479
=> Remove preview flag

package.json
https://github.com/microsoft/vscode-livepreview/pull/703#issuecomment-2552340788
=> Restore preview flag

media/main.js, src/editorPreview/browserPreview.ts, src/editorPreview/webviewComm.ts, tsconfig.json
similar to simple browser where we add a `vscodeBrowserReqId` so we can differentiate webviews.
=> add url search params so we can target the webview

media/main.js, src/editorPreview/browserPreview.ts, src/editorPreview/webviewComm.ts
trigger reload with the new webview id if it doesn't have one and we found the webview id
=> fix how we add webview id to the browser
