- media/inject_script.js
- src/server.ts
- test-workspace/page2.html
External links were only working inside of the internal browser, but were not launching in external browsers. 
Additionally added more listeners to server (more triggers to refresh all connected files).
> Removed Buggy External Link Handling

- media/main.js
- package.json
- src/editorPreview/browserPreview.ts
- src/extension.ts
- src/manager.ts
- src/server/mainServer.ts
Added in this PR:
- HTML files have a button that allows you to open a preview for it.
- `Open Preview` is now split into an option to open the active file or open from the index.
- Re-opening a window with an open preview will re-serialize with at the same page.
- The webview error thrown in the console when closing the preview is fixed.
Closes https://github.com/microsoft/vscode/issues/125775
> Options to Open with Active File

- media/inject_script.html
- media/main.js
- package.json
- src/editorPreview/browserPreview.ts
- src/extension.ts
- src/manager.ts
- src/server/httpServer.ts
- src/server/serverManager.ts
- src/server/serverUtils/contentLoader.ts
- src/server/serverUtils/statusBarNotifier.ts
- src/server/wsServer.ts
- src/task/serverTaskProvider.ts
- src/utils/constants.ts
- src/utils/pathUtil.ts
- src/utils/settingsUtil.ts
- src/utils/utils.ts
- test-workspace/page1.html
- test-workspace/page2.html
Allows for previewing files that are not a part of the current workspace. Also works when a workspace is not opened. 
In multi-root workspaces, the first workspace is where the server is hosted, so anything outside of that is considered a non-workspace or "loose file" preview.
[![Image from Gyazo](https://i.gyazo.com/62079d46ece66bea108dc1f8df470249.gif)](https://gyazo.com/62079d46ece66bea108dc1f8df470249)
Loose files are hosted at a specified endpoint where the whole path except the last pathname is escaped. 
This is to avoid conflicts with existing files in the workspace. Generally, users shouldn't be opening all their files outside workspaces.
By default, the user will be notified on opening a "loose file" preview the first time they do so in a session. They can disable this in …
> Non-workspace Preview

- media/main.js
- package.json
- src/editorPreview/browserPreview.ts
- src/extension.ts
- src/manager.ts
- src/server/httpServer.ts
- src/server/serverManager.ts
- src/server/serverUtils/endpointManager.ts
- src/server/wsServer.ts
- src/utils/pathUtil.ts
Edited endpoints for non-workspace files to:
1. Be shorter.
2. Not reveal any absolute path info.
Since encoding endpoints requires historical data on opened files, reviving webviews on non-workspace previews will just redirect to index.
Also add capabilities in `package.json`
Endpoint example when immediate parent to hosted file is `statichtml_proj`:
> Edited Out-of-workspace Experience

- README.md
- media/main.js
- package-lock.json
- package.json
- src/editorPreview/browserPreview.ts
- src/editorPreview/pageHistoryTracker.ts
- src/extension.ts
- src/manager.ts
- src/multiRootManagers/endpointManager.ts
- src/multiRootManagers/workspaceManager.ts
- src/server/httpServer.ts
- src/server/serverManager.ts
- src/server/serverUtils/contentLoader.ts
- src/server/wsServer.ts
- src/task/serverTaskLinkProvider.ts
- src/task/serverTaskProvider.ts
- src/utils/constants.ts
- src/utils/pathUtil.ts
- src/utils/settingsUtil.ts
Allows the user to select the default workspace for the server root.
Reload is required for the workspace to be used in order to avoid confusion with address changes when the root changes.
The server workspace is configurable in settings.
When nothing is set and multiple workspaces are possible, a notification will open to warn the user.
When the user uses an invalid path, they will be notified upon opening the preview.
Closes https://github.com/microsoft/vscode/issues/126622
> Multi-root Support

- package.json
- src/editorPreview/browserPreview.ts
- src/extension.ts
- src/manager.ts
- src/multiRootManagers/endpointManager.ts
- src/multiRootManagers/workspaceManager.ts
- src/server/httpServer.ts
- src/server/serverManager.ts
- src/server/wsServer.ts
- src/utils/settingsUtil.ts
Can now change server root without reloading. The embedded browser will also auto-redirect the preview to the new endpoint if necessary (and vice versa)
[![Image from Gyazo](https://i.gyazo.com/a4d50b6b6e5df774bc1ce555a0f2bb49.gif)](https://gyazo.com/a4d50b6b6e5df774bc1ce555a0f2bb49)
Also removed post-update settings info message.
Closes https://github.com/microsoft/vscode/issues/127465
Closes https://github.com/microsoft/vscode/issues/127519
> Allow for Workspace Server Root Change w/o Reload

- README.md
- media/vscode.css
- package.json
- src/server/serverManager.ts
- src/server/serverUtils/statusBarNotifier.ts
- src/task/serverTaskTerminal.ts
- src/utils/settingsUtil.ts
Addressing a few misc suggestions from testplan:
Editor context menu to open preview.
Closes https://github.com/microsoft/vscode/issues/127540
`Stop Server` only shows when server is on.
Closes https://github.com/microsoft/vscode/issues/127514
Changed `Force Stop Server` to `Stop Server`.
Closes https://github.com/microsoft/vscode/issues/127512
Replaced mentions of "Pop-ups" with "Notifications"
Closes https://github.com/microsoft/vscode/issues/127474
Show Live Preview commands when clicking on the status bar item.
Closes https://github.com/microsoft/vscode/issues/127472
Hide misc commands from command palette for cleaner look.
Closes https://github.com/microsoft/vscode/issues/127469
Moved context menu position to own section.
Closes https://github.com/microsoft/vscode/issues/127466
Fixed …
> UX Improvements (Misc Testplan Feedback)

- media/inject_script.html
- media/main.js
- package-lock.json
- package.json
- src/editorPreview/browserPreview.ts
- src/editorPreview/pageHistoryTracker.ts
- src/extension.ts
- src/infoManagers/connectionManager.ts
- src/manager.ts
- src/server/httpServer.ts
- src/server/serverManager.ts
- src/server/serverUtils/HTMLInjector.ts
- src/server/wsServer.ts
- src/task/serverTaskProvider.ts
- src/task/serverTaskTerminal.ts
- src/utils/constants.ts
- src/utils/settingsUtil.ts
Previously, the previews were not showing on Codespaces because the local previews were navigating to the host address `127.0.0.1`. Changed the implementation to resolve the external URI instead. Running in Codespaces still has the issue that the local address links occasionally need to actually be opened in an external browser to be accessed and the redirect sequence that it goes through is not render-able within an iframe. However, use with Codespaces works much better now.
Relates to https://github.com/microsoft/vscode/issues/128063
De-coupled the task with external opens, since that might be annoying for some people who want to save screen space.
Closes https://github.com/microsoft/vscode/issues/128148
> Using local addresses for remote + other features

- media/inject_script.html
- media/main.js
- package.json
- src/extension.ts
- src/infoManagers/endpointManager.ts
- src/server/httpServer.ts
- src/server/serverManager.ts
- src/server/serverUtils/contentLoader.ts
- src/utils/settingsUtil.ts
You can now use the command palette to start the server when the extension is not activated. Doing so will pop up a preview, and you can customize which file you want for your initial file:
Command:
Context menu at file explorer and editor:
By default, this will open at the index preview (if nothing else is specified)
Closes #43 
Closes #44 
You can now also preview untitled files (although saving the file will need a re-open of the preview).
[![Image from Gyazo](https://i.gyazo.com/f420937f159677c3ac7bbc1a16d69fa6.gif)](https://gyazo.com/f420937f159677c3ac7bbc1a16d69fa6)
Closes #42
> "Start Server" Command and Untitled File Previewing

- .vscodeignore
Remove media/scripts/linter files from the extension. `.vsix` size **25Mb** => **150Kb**.
> Remove unnecesary files from bundled vsix

- package-lock.json
- package.json
- src/editorPreview/browserPreview.ts
- src/extension.ts
- src/manager.ts
- src/utils/settingsUtil.ts
- removed `atIndex` commands (the same behavior can be done by using the `atFile` command with argument `/`)
- made the debug external preview the default external preview + made it configurable.
> Change default external preview + cleanup

- CHANGELOG.md
- package.json
Change activation from `workspaceContains:**/*.{html,htm,xhtml}` to `onLanguage:html`. If a user wants to activate outside of an HTML file, they can always call `Start Server` and it will open index or the file that the specify in settings (`DefaultPreviewPath`).
Closes #107
> Limit Activation Cases

- package.json
- src/infoManagers/connectionManager.ts
- src/manager.ts
- src/server/httpServer.ts
- src/server/serverManager.ts
- src/server/wsServer.ts
- src/task/serverTaskLinkProvider.ts
- src/task/serverTaskProvider.ts
- src/utils/constants.ts
- src/utils/settingsUtil.ts
Added a setting for custom IP. The extension will check for bad IP formatting or inability to connect. In these cases, it will fall back to `127.0.0.1`.
Closes #97
> add option to configure host IP

- CHANGELOG.md
Changelogs usually have newest releases at the top of the file.
> Reverse the order of changelog

- src/infoManagers/connectionManager.ts
- src/server/serverUtils/HTMLInjector.ts
Addresses were not getting forwarded correctly by the editor when using an IP other than `127.0.0.1` in remote cases. This change makes it so that it always uses `127.0.0.1` when hosting something in a remote instance.
Closes #122
> Use default IP for remote cases

- CHANGELOG.md
This fixes potential markdown rendering issue (and makes it easier to read and more consistent with the other releases)
> Add a line break between releases on CHANGELOG

- media/injectScript.js
resolve #129 @mjbvz @andreamah 
use an event listener to check for errors and logs them in the output console.
> Print Exception in Console

- media/injectScript.js
resolve #128 @mjbvz @andreamah 
```javascript
JSON.stringify(()=>{}) 
```
produces undefined instead of an error.
Checks if stringifiedMsg is undefined and throw an error.
> Fixed Functions Printed as Undefined

- README.md
- media/injectScript.js
- media/main.js
TLDR; If the attribute `data-server-no-reload` is found on the `<body>` tag, commands to reload the page are ignored.
At the moment, all browser windows are reloaded when there is a source change, regardless of whether the source change affects them. This is a robust, base logic.
However, there are instances where one wants to prevent a page from being reloaded by changes. Eg, if _a.html_ opens up a connection to a media device, a change in _b.html_ will cause _a.html_ to be perhaps unnecessarily reloaded. This requires a manual re-starting of the stream, and other state may be lost.
This addition changes the injection script to check for the presence of an attribute on the `BODY` element. If it's there, the reload requests are ignored, and the page will have to be manually reloaded. The …
> Per-page reload opt-out

- media/main.js
- src/extension.ts
- src/server/serverUtils/HTMLInjector.ts
It still doesn't work (doesn't refresh after the load no matter the settings) but at least the console is clean. 
Please never use ``for in`` - you risk to tap into inherited properties of the array/object. It's not even less code at this point.
> fix iteration over inhereted array props; prop parent existance checks

- src/server/httpServer.ts
- src/server/serverUtils/contentLoader.ts
Fixes #144
I believe that the `Content-Type: charset=UTF-8` flag is no longer needed for hosting if it's not a `text/` mimetype.
Tested with the code from [this tutorial](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming)
> Remove hardcoded UTF-8 content type

- CHANGELOG.md
Unicode should be capitalized
https://en.wikipedia.org/wiki/Unicode
> Unicode should be capitalized in CHANGELOG

- package.json
- package.nls.json
- src/server/serverGrouping.ts
- src/task/serverTaskProvider.ts
- src/task/serverTaskTerminal.ts
- src/utils/settingsUtil.ts
Fixes #307
Fixes #278
Fixes #260
- Remove the non `--verbose` option for tasks.
- tasks don't launch on default for external browser
- Other task cleanup
> Refine task process to make more sense

- .vscode/tasks.json
- package.json
- package.nls.json
- src/extension.ts
Fixes #388
Also added a sample tasks.json for using the command.
> Enable start server from absolute/relative filename

- package.json
- package.nls.json
- src/connectionInfo/connection.ts
- src/connectionInfo/connectionManager.ts
- src/editorPreview/browserPreview.ts
- src/extension.ts
- src/infoManagers/endpointManager.ts
- src/manager.ts
- src/server/httpServer.ts
- src/server/wsServer.ts
- src/task/serverTaskLinkProvider.ts
- src/updateListener.ts
- src/utils/pathUtil.ts
- src/utils/settingsUtil.ts
Fixes #155
Fixes #408
Fixes #409
If the `serverRoot` setting is set and appending it to the current workspace makes sense (the directory path exists relative to the workspace root), then all relative paths will be relative to that server root offset.
> Add option to choose root offset for previews

- package.nls.json
- src/utils/externalBrowserUtils.ts
Fixes #414
Codespaces can't process the calls to `open`, nor does it throw an error, so force it to use vscode API to open new window.
> use default external browser in web

- media/main.js
- src/connectionInfo/connection.ts
- src/editorPreview/browserPreview.ts
- src/editorPreview/previewManager.ts
- src/editorPreview/webviewComm.ts
- src/infoManagers/endpointManager.ts
- src/manager.ts
- src/server/httpServer.ts
- src/server/serverUtils/contentLoader.ts
- src/server/wsServer.ts
- src/utils/pathUtil.ts
Fixes #326
Fixes #444 
Cleaning up a lot of hacky path mangling.
UNC paths will look like this:
Using slashes or encodings of slashes (ie: `%5C%5C`) causes complicated path handling when browsers automatically simplify the path, so I'm using a special endpoint (`/unc`) to deal with UNC paths.
> Fix bug when previewing UNC files and path refactoring

- package.json
- package.nls.json
- src/updateListener.ts
- src/utils/settingsUtil.ts
Fixes #174
Adds setting- `livePreview.previewDebounceDelay`, which defaults to 50 and makes things a lot smoother with lots of changes.
> Add customizable debounce delay to preview

- src/extension.ts
- src/manager.ts
> Use active workspace when using `livePreview.start`

- media/injectScript.js
#449
Fixes https://github.com/microsoft/vscode-livepreview/issues/508
What `createConsoleOverride` does is just to call `postParentMessage` before calling console output methods, but if `window.parent === window` `postParentMessage` does nothing, so should we override console only if `window.parent !== window`? At least this fixes the issue in external browser.
> fix console line number in external browser

- src/connectionInfo/connection.ts
- src/server/httpServer.ts
Fixes #546
Seems that codespaces might have changed how the host header looked from what it was when https://github.com/microsoft/vscode-livepreview/pull/366 was implemented.
> Codespaces 401

- src/connectionInfo/connection.ts
Fixes #546
The fix in #554 didn't account for another call to asExternalURI.
> isolate asExternalURI work to connection.ts

- build/pre-release.yml
To mitigate the 401 error in downloading mime package in prerelease pipeline
> use public npm registry in prerelease
